-- Audio generation (INTELLIGENCE_PLAN.md Phase 5-6; owner: "sounds auto-detected from the script, suggested to
-- generate, including background music"). Audio Studio owns the request: generate sound for a planned cue (ambience,
-- effect, Foley, score) with a backend from the Provider Gateway — AuraStage's built-in synthesiser today, paid
-- providers when their keys are added. A worker makes the file; the Assets domain registers it (its own internal
-- function below), linked to the scene; the person then chooses to use it on the cue. Nothing is placed or replaced
-- automatically (rule 11).

-- ---- Assets domain: a file generated by a worker on someone's behalf ------------------------------------------
create or replace function app_private.register_generated_asset(p_project uuid, p_created_by uuid, p_type text, p_name text,
  p_storage_path text, p_checksum text, p_metadata jsonb, p_note text, p_scene uuid)
returns uuid
language plpgsql security definer set search_path = '' as $$
declare v_org uuid; v_id uuid;
begin
  select org_id into v_org from public.projects where id = p_project;
  if v_org is null then raise exception 'AURA-AST-404: project not found' using errcode = 'P0404'; end if;
  insert into public.assets(org_id, project_id, type, name, storage_path, checksum, metadata, created_by, description, tags)
  values (v_org, p_project, p_type, left(p_name, 200), p_storage_path, p_checksum, coalesce(p_metadata, '{}'::jsonb), p_created_by,
          left(coalesce(p_note, ''), 2000), array['generated'])
  returning id into v_id;
  update public.asset_versions set note = left(coalesce(p_note, 'Generated'), 500) where asset_id = v_id and version_number = 1;
  if p_scene is not null then
    insert into public.asset_links(org_id, project_id, asset_id, object_type, object_id, created_by)
    values (v_org, p_project, v_id, 'scene', p_scene, p_created_by) on conflict do nothing;
  end if;
  insert into public.audit_events(org_id, actor_id, action, object_type, object_id, metadata)
  values (v_org, p_created_by, 'AssetRegistered', 'Asset', v_id, jsonb_build_object('type', p_type, 'name', p_name, 'generated', true, 'size', p_metadata->'size_bytes'));
  return v_id;
end;
$$;
revoke all on function app_private.register_generated_asset(uuid, uuid, text, text, text, text, jsonb, text, uuid) from public, anon, authenticated;

-- ---- Audio Studio: generation requests --------------------------------------------------------------------------
create table if not exists public.audio_generations (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,
  scene_id uuid not null references public.scenes(id) on delete cascade,
  session_id uuid references public.audio_sessions(id) on delete set null,
  -- The planned cue this is for (kept even if the cue is later re-spotted away: provenance).
  clip_id uuid references public.audio_clips(id) on delete set null,
  kind text not null check (kind in ('ambience','fx','foley','score','voice')),
  description text not null check (char_length(description) between 1 and 500),
  duration_seconds numeric not null check (duration_seconds > 0 and duration_seconds <= 300),
  mood text[] not null default '{}',
  provider text not null,
  model text not null,
  execution text not null check (execution in ('native','local','external','test')),
  seed int not null default 1,
  params jsonb not null default '{}'::jsonb,
  status text not null default 'queued' check (status in ('queued','running','succeeded','failed')),
  asset_id uuid references public.assets(id) on delete set null,
  -- What the backend actually made (layers, loudness, voice…), for the "why" shown next to the file.
  result jsonb,
  error text,
  engine_version text not null,
  job_id uuid references public.jobs(id) on delete set null,
  provider_request_id text,
  cost_usd numeric,
  attempt int not null default 0,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz
);
create index if not exists idx_audio_generations_scene on public.audio_generations(scene_id, created_at desc);
create index if not exists idx_audio_generations_queue on public.audio_generations(status, created_at) where status in ('queued','running');
alter table public.audio_generations enable row level security;
drop policy if exists audio_generations_select on public.audio_generations;
create policy audio_generations_select on public.audio_generations for select
  using (project_id = any ((select public.my_project_ids())::uuid[]));

create or replace function public.request_audio_generation(p_project uuid, p_scene uuid, p_clip uuid, p_kind text, p_description text,
  p_duration numeric, p_mood text[], p_provider text, p_model text, p_execution text, p_seed int, p_params jsonb, p_engine_version text)
returns public.audio_generations
language plpgsql security definer set search_path = public as $$
declare v public.audio_generations; v_org uuid; v_session uuid; v_job uuid;
begin
  perform public.gate_write(p_project, 'audio', 'generate');
  select org_id into v_org from public.scenes where id = p_scene and project_id = p_project;
  if v_org is null then raise exception 'AURA-AUD-404: scene not found in this project' using errcode = 'P0404'; end if;
  select id into v_session from public.audio_sessions where scene_id = p_scene;
  if p_clip is not null and not exists (select 1 from public.audio_clips where id = p_clip and session_id = v_session) then
    raise exception 'AURA-AUD-404: that cue isn''t in this scene''s session' using errcode = 'P0404';
  end if;
  if (select count(*) from public.audio_generations where created_by = auth.uid() and created_at > now() - interval '1 minute') >= 30 then
    raise exception 'AURA-AUD-429: that''s a lot of generations in a minute — give it a moment' using errcode = 'P0429';
  end if;
  insert into public.jobs(org_id, project_id, engine_id, engine_version, input_snapshot)
  values (v_org, p_project, 'audio.generate', p_engine_version, jsonb_build_object('kind', p_kind, 'provider', p_provider, 'clip_id', p_clip))
  returning id into v_job;
  insert into public.audio_generations(org_id, project_id, scene_id, session_id, clip_id, kind, description, duration_seconds, mood, provider, model,
    execution, seed, params, engine_version, job_id, created_by)
  values (v_org, p_project, p_scene, v_session, p_clip, p_kind, left(trim(p_description), 500), p_duration, coalesce(p_mood, '{}'), p_provider, p_model,
    p_execution, coalesce(p_seed, 1), coalesce(p_params, '{}'), p_engine_version, v_job, auth.uid())
  returning * into v;
  insert into public.audit_events(org_id, actor_id, action, object_type, object_id, metadata)
  values (v_org, auth.uid(), 'AudioGenerationRequested', 'AudioGeneration', v.id, jsonb_build_object('kind', p_kind, 'provider', p_provider, 'execution', p_execution));
  return v;
end;
$$;

create or replace function public.worker_claim_audio_generation(p_token text)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare v public.audio_generations;
begin
  perform public.worker_check(p_token);
  select * into v from public.audio_generations
    where status = 'queued' or (status = 'running' and started_at < now() - interval '15 minutes' and attempt < 3)
    order by created_at limit 1 for update skip locked;
  if v.id is null then return null; end if;
  update public.audio_generations set status = 'running', attempt = attempt + 1, started_at = now() where id = v.id returning * into v;
  update public.jobs set status = 'running', attempt = v.attempt, started_at = now() where id = v.job_id;
  return to_jsonb(v);
end;
$$;

create or replace function public.worker_complete_audio_generation(p_token text, p_id uuid, p_storage_key text, p_checksum text,
  p_metadata jsonb, p_result jsonb, p_request_id text, p_cost numeric)
returns uuid
language plpgsql security definer set search_path = public as $$
declare v public.audio_generations; v_asset uuid; v_label text;
begin
  perform public.worker_check(p_token);
  select * into v from public.audio_generations where id = p_id and status = 'running' for update;
  if v.id is null then return (select asset_id from public.audio_generations where id = p_id); end if; -- idempotent
  perform set_config('aura.project_id', v.project_id::text, true); -- audit rows carry the project
  v_label := initcap(v.kind) || ' — ' || left(v.description, 150);
  v_asset := app_private.register_generated_asset(v.project_id, v.created_by, 'audio', v_label, p_storage_key, p_checksum,
    p_metadata || jsonb_build_object('generated', jsonb_build_object('generation_id', v.id, 'provider', v.provider, 'model', v.model, 'execution', v.execution, 'engine_version', v.engine_version)),
    'Generated by ' || v.provider || ' (' || v.model || ') for: ' || left(v.description, 300), v.scene_id);
  update public.audio_generations set status = 'succeeded', asset_id = v_asset, result = p_result, completed_at = now(),
    provider_request_id = p_request_id, cost_usd = p_cost, error = null where id = v.id;
  update public.jobs set status = 'completed', completed_at = now(), provider_request_id = p_request_id, cost_actual = p_cost,
    output_refs = jsonb_build_object('asset_id', v_asset) where id = v.job_id;
  insert into public.audit_events(org_id, actor_id, action, object_type, object_id, metadata)
  values (v.org_id, v.created_by, 'AudioGenerated', 'AudioGeneration', v.id, jsonb_build_object('asset_id', v_asset, 'provider', v.provider));
  return v_asset;
end;
$$;

create or replace function public.worker_fail_audio_generation(p_token text, p_id uuid, p_error text, p_request_id text)
returns void
language plpgsql security definer set search_path = public as $$
declare v public.audio_generations;
begin
  perform public.worker_check(p_token);
  update public.audio_generations set status = 'failed', error = left(coalesce(p_error, 'Generation failed'), 1000), completed_at = now(), provider_request_id = p_request_id
    where id = p_id and status = 'running' returning * into v;
  if v.id is null then return; end if;
  update public.jobs set status = 'failed', completed_at = now(), error = jsonb_build_object('message', left(p_error, 500)) where id = v.job_id;
end;
$$;

revoke execute on function public.request_audio_generation(uuid, uuid, uuid, text, text, numeric, text[], text, text, text, int, jsonb, text) from public, anon;
grant execute on function public.request_audio_generation(uuid, uuid, uuid, text, text, numeric, text[], text, text, text, int, jsonb, text) to authenticated;
revoke execute on function public.worker_claim_audio_generation(text), public.worker_complete_audio_generation(text, uuid, text, text, jsonb, jsonb, text, numeric),
  public.worker_fail_audio_generation(text, uuid, text, text) from public, authenticated;
grant execute on function public.worker_claim_audio_generation(text), public.worker_complete_audio_generation(text, uuid, text, text, jsonb, jsonb, text, numeric),
  public.worker_fail_audio_generation(text, uuid, text, text) to anon;
