// Places the world's stories are set in, with the English accent a local speaker commonly has on screen and the
// languages widely spoken there. A suggestion for the writer, never a fact about a person: people everywhere speak in
// many ways, and the writer decides. Order matters — more specific places first.
export interface Region { id: string; place: string; re: RegExp; accent: string; languages: string[] }
const r = (id: string, place: string, re: RegExp, accent: string, languages: string[]): Region => ({ id, place, re, accent, languages });

export const REGIONS: Region[] = [
  // Africa
  r("ng-lagos", "Lagos", /\b(lagos|ikeja|lekki|surulere|yaba|victoria island|ibadan|abeokuta|yoruba(land)?)\b/i, "Nigerian English (south-west, Lagos)", ["English", "Yoruba", "Nigerian Pidgin"]),
  r("ng-north", "Northern Nigeria", /\b(kano|kaduna|sokoto|maiduguri|zaria|hausa(land)?)\b/i, "Nigerian English (northern)", ["Hausa", "English", "Arabic"]),
  r("ng-east", "South-east Nigeria", /\b(enugu|onitsha|owerri|aba|igbo(land)?|port harcourt|calabar)\b/i, "Nigerian English (south-east)", ["English", "Igbo", "Nigerian Pidgin"]),
  r("ng", "Nigeria", /\b(nigeria|nigerian|abuja|naija)\b/i, "Nigerian English", ["English", "Nigerian Pidgin", "Yoruba", "Hausa", "Igbo"]),
  r("gh", "Ghana", /\b(ghana|ghanaian|accra|kumasi|tamale)\b/i, "Ghanaian English", ["English", "Twi", "Ga", "Ewe"]),
  r("ke", "Kenya", /\b(kenya|kenyan|nairobi|mombasa|kisumu)\b/i, "Kenyan English", ["English", "Swahili"]),
  r("tz", "Tanzania", /\b(tanzania|tanzanian|dar es salaam|zanzibar|arusha)\b/i, "Tanzanian English", ["Swahili", "English"]),
  r("ug", "Uganda", /\b(uganda|ugandan|kampala)\b/i, "Ugandan English", ["English", "Luganda", "Swahili"]),
  r("et", "Ethiopia", /\b(ethiopia|ethiopian|addis ababa)\b/i, "Ethiopian English", ["Amharic", "Oromo", "English"]),
  r("za", "South Africa", /\b(south africa|south african|johannesburg|joburg|soweto|cape town|durban|pretoria)\b/i, "South African English", ["English", "isiZulu", "isiXhosa", "Afrikaans"]),
  r("zw", "Zimbabwe", /\b(zimbabwe|zimbabwean|harare|bulawayo)\b/i, "Zimbabwean English", ["English", "Shona", "Ndebele"]),
  r("sn", "Senegal", /\b(senegal|senegalese|dakar)\b/i, "Senegalese French-accented English", ["Wolof", "French"]),
  r("cm", "Cameroon", /\b(cameroon|cameroonian|douala|yaound[eé])\b/i, "Cameroonian English", ["French", "English", "Cameroonian Pidgin"]),
  r("cd", "DR Congo", /\b(congo|congolese|kinshasa|lubumbashi)\b/i, "Congolese French-accented English", ["French", "Lingala", "Swahili"]),
  r("eg", "Egypt", /\b(egypt|egyptian|cairo|alexandria)\b/i, "Egyptian Arabic-accented English", ["Egyptian Arabic", "English"]),
  r("ma", "Morocco", /\b(morocco|moroccan|casablanca|marrakesh|marrakech|rabat|fez)\b/i, "Moroccan-accented English", ["Moroccan Arabic (Darija)", "Amazigh", "French"]),
  // Europe
  r("gb-scot", "Scotland", /\b(scotland|scottish|glasgow|edinburgh|aberdeen|dundee|highlands)\b/i, "Scottish English", ["English", "Scots"]),
  r("gb-wales", "Wales", /\b(wales|welsh|cardiff|swansea)\b/i, "Welsh English", ["English", "Welsh"]),
  r("gb-ni", "Northern Ireland", /\b(belfast|derry|northern ireland)\b/i, "Northern Irish English", ["English"]),
  r("ie", "Ireland", /\b(ireland|irish|dublin|cork|galway|limerick)\b/i, "Irish English", ["English", "Irish"]),
  r("gb-north", "Northern England", /\b(manchester|liverpool|leeds|newcastle|sheffield|yorkshire|lancashire)\b/i, "Northern English", ["English"]),
  r("gb-london", "London", /\b(london|peckham|brixton|hackney|east end|south london|croydon)\b/i, "London English (Multicultural London English or Estuary)", ["English"]),
  r("gb", "England", /\b(england|english|britain|british|birmingham|bristol|oxford|cambridge|uk)\b/i, "British English (Southern Standard)", ["English"]),
  r("fr", "France", /\b(france|french|paris|marseille|lyon|bordeaux)\b/i, "French-accented English", ["French"]),
  r("de", "Germany", /\b(germany|german|berlin|munich|hamburg|frankfurt)\b/i, "German-accented English", ["German"]),
  r("it", "Italy", /\b(italy|italian|rome|milan|naples|sicily|florence|venice)\b/i, "Italian-accented English", ["Italian"]),
  r("es", "Spain", /\b(spain|spanish|madrid|barcelona|seville|valencia)\b/i, "Spanish-accented English (Spain)", ["Spanish", "Catalan"]),
  r("pt", "Portugal", /\b(portugal|portuguese|lisbon|porto)\b/i, "Portuguese-accented English", ["Portuguese"]),
  r("ru", "Russia", /\b(russia|russian|moscow|st\.? petersburg)\b/i, "Russian-accented English", ["Russian"]),
  r("ua", "Ukraine", /\b(ukraine|ukrainian|kyiv|kiev|odesa|odessa|lviv)\b/i, "Ukrainian-accented English", ["Ukrainian", "Russian"]),
  r("pl", "Poland", /\b(poland|polish|warsaw|krak[oó]w)\b/i, "Polish-accented English", ["Polish"]),
  r("nl", "Netherlands", /\b(netherlands|dutch|amsterdam|rotterdam)\b/i, "Dutch-accented English", ["Dutch"]),
  r("se", "Scandinavia", /\b(sweden|swedish|stockholm|norway|norwegian|oslo|denmark|danish|copenhagen)\b/i, "Scandinavian-accented English", ["Swedish", "Norwegian", "Danish"]),
  r("gr", "Greece", /\b(greece|greek|athens|thessaloniki)\b/i, "Greek-accented English", ["Greek"]),
  r("tr", "Turkey", /\b(turkey|t[uü]rkiye|turkish|istanbul|ankara)\b/i, "Turkish-accented English", ["Turkish"]),
  // Americas
  r("us-south", "the American South", /\b(texas|georgia|alabama|mississippi|louisiana|tennessee|atlanta|new orleans|nashville|houston)\b/i, "Southern American English", ["English"]),
  r("us-ny", "New York", /\b(new york|nyc|brooklyn|bronx|queens|manhattan|harlem)\b/i, "New York English", ["English"]),
  r("us-boston", "Boston", /\b(boston|massachusetts)\b/i, "Boston English", ["English"]),
  r("us", "the United States", /\b(america|american|usa|united states|los angeles|chicago|california|san francisco|seattle|miami|washington dc)\b/i, "General American English", ["English"]),
  r("ca", "Canada", /\b(canada|canadian|toronto|vancouver|montreal|ottawa)\b/i, "Canadian English", ["English", "French"]),
  r("jm", "Jamaica", /\b(jamaica|jamaican|kingston)\b/i, "Jamaican English", ["English", "Jamaican Patois"]),
  r("tt", "Trinidad and Tobago", /\b(trinidad|tobago|port of spain)\b/i, "Trinidadian English", ["English", "Trinidadian Creole"]),
  r("mx", "Mexico", /\b(mexico|mexican|guadalajara|monterrey|oaxaca|tijuana)\b/i, "Mexican Spanish-accented English", ["Spanish"]),
  r("br", "Brazil", /\b(brazil|brazilian|s[aã]o paulo|rio de janeiro|salvador|bras[ií]lia)\b/i, "Brazilian Portuguese-accented English", ["Portuguese"]),
  r("ar", "Argentina", /\b(argentina|argentine|argentinian|buenos aires)\b/i, "Argentine Spanish-accented English", ["Spanish"]),
  r("co", "Colombia", /\b(colombia|colombian|bogot[aá]|medell[ií]n|cali)\b/i, "Colombian Spanish-accented English", ["Spanish"]),
  // Asia & Middle East
  r("in-south", "South India", /\b(chennai|bangalore|bengaluru|hyderabad|kerala|tamil nadu)\b/i, "South Indian English", ["English", "Tamil", "Telugu", "Kannada", "Malayalam"]),
  r("in", "India", /\b(india|indian|mumbai|bombay|delhi|kolkata|calcutta|punjab|pune)\b/i, "Indian English", ["Hindi", "English"]),
  r("pk", "Pakistan", /\b(pakistan|pakistani|karachi|lahore|islamabad)\b/i, "Pakistani English", ["Urdu", "Punjabi", "English"]),
  r("bd", "Bangladesh", /\b(bangladesh|bangladeshi|dhaka|chittagong)\b/i, "Bangladeshi English", ["Bengali", "English"]),
  r("lk", "Sri Lanka", /\b(sri lanka|sri lankan|colombo)\b/i, "Sri Lankan English", ["Sinhala", "Tamil", "English"]),
  r("cn", "China", /\b(china|chinese|beijing|shanghai|guangzhou|shenzhen)\b/i, "Mandarin-accented English", ["Mandarin Chinese"]),
  r("hk", "Hong Kong", /\b(hong kong)\b/i, "Hong Kong English", ["Cantonese", "English"]),
  r("jp", "Japan", /\b(japan|japanese|tokyo|osaka|kyoto)\b/i, "Japanese-accented English", ["Japanese"]),
  r("kr", "Korea", /\b(korea|korean|seoul|busan)\b/i, "Korean-accented English", ["Korean"]),
  r("ph", "the Philippines", /\b(philippines|filipino|filipina|manila|cebu)\b/i, "Philippine English", ["Filipino (Tagalog)", "English"]),
  r("sg", "Singapore", /\b(singapore|singaporean)\b/i, "Singapore English", ["English", "Mandarin Chinese", "Malay", "Tamil"]),
  r("id", "Indonesia", /\b(indonesia|indonesian|jakarta|bali)\b/i, "Indonesian-accented English", ["Indonesian"]),
  r("vn", "Vietnam", /\b(vietnam|vietnamese|hanoi|ho chi minh|saigon)\b/i, "Vietnamese-accented English", ["Vietnamese"]),
  r("il", "Israel", /\b(israel|israeli|tel aviv|jerusalem|haifa)\b/i, "Israeli-accented English", ["Hebrew", "Arabic"]),
  r("lb", "Lebanon", /\b(lebanon|lebanese|beirut)\b/i, "Lebanese-accented English", ["Lebanese Arabic", "French"]),
  r("gulf", "the Gulf", /\b(dubai|abu dhabi|uae|emirati|qatar|doha|saudi|riyadh|jeddah|kuwait|bahrain|oman)\b/i, "Gulf Arabic-accented English", ["Arabic", "English"]),
  r("ir", "Iran", /\b(iran|iranian|persian|tehran)\b/i, "Persian-accented English", ["Persian (Farsi)"]),
  // Oceania
  r("au", "Australia", /\b(australia|australian|sydney|melbourne|brisbane|perth|adelaide)\b/i, "Australian English", ["English"]),
  r("nz", "New Zealand", /\b(new zealand|kiwi|auckland|wellington|christchurch|aotearoa)\b/i, "New Zealand English", ["English", "Māori"]),
];
